### ISSUE TITLE
dev/reset stops working when start replacement fn from README is swapped

### ISSUE THREAD

**Issue by tvanhens** [milesian/system-diagrams#2]
When I swap out the start fn in the dev namespace with the start function from the docs, my system no longer starts. I get the following error:

ClassCastException datomic.peer.LocalConnection cannot be cast to clojure.lang.IObj  clojure.core/with-meta--4109 (core.clj:216)

If I remove the components in the system that I have isolated this error to, I can get my system to start. However, no http kit webservice components get served up as far as I can tell.

Are there any conventions or guidelines for how to structure your system map to be compatible with system-diagrams?

**Comment by tangrammer** [comment]
Hi Tyler, could you paste here your original dev/start fn?

**Comment by tangrammer** [comment]
As It seems that it's the same issue as https://github.com/milesian/BigBang/issues/1 try to check the project proposal too

**Comment by tvanhens** [comment]
Thanks. I'll follow it over there. Looks like exactly the same issue as I'm using juxt.modular/datomic as well.

**Comment by tangrammer** [comment]
Hi @tvanhens , is this issue solved with last modular PR merged? https://github.com/juxt/modular/pull/20

**Comment by tvanhens** [comment]
I will check either later today or tomorrow, depending on how the time goes and let you know. Thanks for the update :)

**Comment by tangrammer** [comment]
Fixed with juxt/modular#20
